/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.vianna.trabalho_fpoo_bda.view.report;

import br.edu.vianna.trabalho_fpoo_bda.model.Report;

/**
 *
 * @author breno
 */
public class ReportView extends javax.swing.JDialog {

    /**
     * Creates new form ReportView
     */
    public ReportView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jlblPacientes_Testes = new javax.swing.JLabel();
        jlblDetectados = new javax.swing.JLabel();
        jlblNaoDetectados = new javax.swing.JLabel();
        jlblRecoleta_Motivo = new javax.swing.JLabel();
        jlblExameInconclusivo = new javax.swing.JLabel();
        jlblExameInvalido = new javax.swing.JLabel();
        jlblSignature = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cantarell Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Du Gustin Clínicas");

        lblData.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblData.setForeground(new java.awt.Color(51, 51, 51));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("Relatório diário - ");

        jlblPacientes_Testes.setForeground(new java.awt.Color(51, 51, 51));
        jlblPacientes_Testes.setText("lblPacientes_Testes");

        jlblDetectados.setForeground(new java.awt.Color(51, 51, 51));
        jlblDetectados.setText("jlblDetectados");

        jlblNaoDetectados.setForeground(new java.awt.Color(51, 51, 51));
        jlblNaoDetectados.setText("jlblNaoDetectados");

        jlblRecoleta_Motivo.setForeground(new java.awt.Color(51, 51, 51));
        jlblRecoleta_Motivo.setText("jlblRecoleta_Motivo");

        jlblExameInconclusivo.setForeground(new java.awt.Color(51, 51, 51));
        jlblExameInconclusivo.setText("jlblExameInconclusivo");

        jlblExameInvalido.setForeground(new java.awt.Color(51, 51, 51));
        jlblExameInvalido.setText("jlblExameInvalido");

        jlblSignature.setForeground(new java.awt.Color(51, 51, 51));
        jlblSignature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSignature.setText("_______________________________________");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Responsável técnico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblDetectados)
                                    .addComponent(jlblPacientes_Testes)
                                    .addComponent(jlblNaoDetectados)
                                    .addComponent(jlblRecoleta_Motivo)
                                    .addComponent(jlblExameInconclusivo)
                                    .addComponent(jlblExameInvalido))))
                        .addGap(0, 98, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jlblSignature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)))
                .addGap(20, 20, 20)
                .addComponent(lblData)
                .addGap(43, 43, 43)
                .addComponent(jlblPacientes_Testes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblDetectados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNaoDetectados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblRecoleta_Motivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblExameInconclusivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblExameInvalido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jlblSignature)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReportView dialog = new ReportView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void showReport(Report r) {
        // Coloca os valores no report
        jlblPacientes_Testes.setText(String.format("%s pacientes atendidos (%s testes utilizados)", r.getPacientesAtendidos(), r.getTestesUtilizados()));
        jlblDetectados.setText(String.format("%s Exames \"Detectado\"", r.getExamesDetectados()));
        jlblNaoDetectados.setText(String.format("%s Exames \"Não Detectado\"", r.getExamesNaoDetectados()));
        jlblRecoleta_Motivo.setText(String.format("%s Pacientes para a recoleta", r.getPacientesRecoleta()));
        jlblExameInconclusivo.setText(String.format("%s Pacientes com exames inconclusivos e os testes foram refeitos", r.getExamesInconclusivos()));
        jlblExameInvalido.setText(String.format("%s  com exames inválidos", r.getExamesInvalidos()));
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblDetectados;
    private javax.swing.JLabel jlblExameInconclusivo;
    private javax.swing.JLabel jlblExameInvalido;
    private javax.swing.JLabel jlblNaoDetectados;
    private javax.swing.JLabel jlblPacientes_Testes;
    private javax.swing.JLabel jlblRecoleta_Motivo;
    private javax.swing.JLabel jlblSignature;
    private javax.swing.JLabel lblData;
    // End of variables declaration//GEN-END:variables
}
